# https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_create_environment: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      rustup default nightly

python:
  install:
    - method: pip
      path: .
