[package]
name = "starlark-pyo3"
version = "0.1.0"
authors = ["Andreas Kloeckner <inform@tiker.net>"]
license = "MIT"

description = "Python bindings for starlark-rust"
homepage = "https://github.com/inducer/starlark-pyo3"
repository = "https://github.com/inducer/starlark-pyo3"
readme = "README.md"

[lib]
crate-type = ["cdylib"]
name = "starlark"

[package.metadata.maturin]
classifier = [
  "Programming Language :: Rust",
]

requires-python = ">=3.6"

[dependencies]
starlark = { git = 'https://github.com/facebookexperimental/starlark-rust.git' }
anyhow = "^1.0.65"
pyo3 = { version = "0.17.1", features = ["extension-module"] }
syn = "^1.0.96"
ouroboros = "0.15.5"

[patch.crates-io]
starlark = { git = 'https://github.com/facebookexperimental/starlark-rust/' }
